spring:
   profiles:
      active:
      - dev
---
spring:
  profiles: dev
  application:
      name: microconfig-test-dev

---
spring:
  profiles: hahaha
  application:
      name: microconfig-test-hahaha
